const data = {
  products: [
    {
      _id: '1',
      name: 'Avacado',
      category: 'fruit,plant',
      image: '/images/avacado.jpg',
      price: 120,
      countInStock: 10,
      brand: '',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '2',
      name: 'Apple seed',
      category: 'tree,fruit',
      image: '/images/apple.jpg',
      price: 100,
      countInStock: 20,
      brand: '',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '3',
      name: ' carrot seed',
      category: 'underground,vegetable',
      image: '/images/carrot.jpg',
      price: 220,
      countInStock: 0,
      brand: '',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      _id: '4',
      name: 'Sunflower seeds',
      category: '',
      image: '/images/sunflower.jpg',
      price: 78,
      countInStock: 15,
      brand: '',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      _id: '5',
      name: ',j bk',
      category: '',
      image: '/images/p5.jpg',
      price: 65,
      countInStock: 5,
      brand: '',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      _id: '6',
      name: 'mango seed',
      category: '',
      image: '/images/p6.jpg',
      price: 139,
      countInStock: 12,
      brand: '',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
  ],
};
export default data;
